name: Python application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests

  process-images:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tesseract and language data files
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr
        sudo apt-get install -y tesseract-ocr-eng tesseract-ocr-tha
        export TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
        echo "TESSDATA_PREFIX set to $TESSDATA_PREFIX"

    - name: Process images to CSV
      run: |
        mkdir -p data/output
        cd src
        python main.py data/images data/output
        cd ..

    - name: Upload CSV files
      uses: actions/upload-artifact@v2
      with:
        name: csv-files
        path: data/output/*.csv
