name: Python application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover tests

  process-images:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Tesseract and language data files
      run: |
        sudo mkdir -p /opt/hostedtoolcache/tessdata
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr
        sudo apt-get install -y tesseract-ocr-eng tesseract-ocr-tha
        sudo cp /usr/share/tesseract-ocr/4.00/tessdata/* /opt/hostedtoolcache/tessdata/
      env:
        TESSDATA_PREFIX: /opt/hostedtoolcache/tessdata

    - name: Verify Tesseract installation
      run: |
        echo "Tesseract version:"
        tesseract --version
        echo "TESSDATA_PREFIX is set to:"
        echo $TESSDATA_PREFIX
        echo "Contents of the tessdata directory:"
        ls $TESSDATA_PREFIX
      env:
        TESSDATA_PREFIX: /opt/hostedtoolcache/tessdata

    - name: Process images to CSV
      run: |
        mkdir -p data/output
        python src/main.py data/images data/output

    - name: Upload CSV files
      uses: actions/upload-artifact@v2
      with:
        name: csv-files
        path: data/output/*.csv
